config/routes.rb
Rails.application.routes.draw do
  get 'explore/if_they_recycle'
  get 'explore/amount_of_garbage'
  get 'explore/satisfaction'
  get 'explore/table_of_contents'
  get 'explore/analysis'
  get 'team_data/load'
  get 'participants/index'
  get 'recyclers/index'
  get 'non_recyclers/index'
  
  resources :participants
  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :non_recyclers
  resources :recyclers
  resources :blogs
  
  root to: "explore#table_of_contents"
  
  
end

app/models/participant.rb
class Participant < ApplicationRecord
has_one :non_recycler
has_one :recycler

end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  before_action :set_participant, only: [:show, :edit, :update, :destroy]
  
  

  # GET /participants
  # GET /participants.json
  def index
    @participants = Participant.all
  end
  
  # GET /participants/1
  # GET /participants/1.json
  def show
  end

  # GET /participants/new
  def new
    @participant = Participant.new
  end

  # GET /participants/1/edit
  def edit
  end

  # POST /participants
  # POST /participants.json
  def create
    @participant = Participant.new(participant_params)

    respond_to do |format|
      if @participant.save
        format.html { redirect_to @participant, notice: 'Participant was successfully created.' }
        format.json { render :show, status: :created, location: @participant }
      else
        format.html { render :new }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /participants/1
  # PATCH/PUT /participants/1.json
  def update
    respond_to do |format|
      if @participant.update(participant_params)
        format.html { redirect_to @participant, notice: 'Participant was successfully updated.' }
        format.json { render :show, status: :ok, location: @participant }
      else
        format.html { render :edit }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /participants/1
  # DELETE /participants/1.json
  def destroy
    @participant.destroy
    respond_to do |format|
      format.html { redirect_to participants_url, notice: 'Participant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_participant
      @participant = Participant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def participant_params
      params.require(:participant).permit(:location, :duration_of_stay, :amount_of_garbage, :recycling_knowledge1, :recycling_knowledge2, :if_they_recycle, :if_they_recycle_in_IGC)
    end
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/views/participants/_form.html.erb
<%= form_with(model: participant, local: true) do |form| %>
  <% if participant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(participant.errors.count, "error") %> prohibited this participant from being saved:</h2>

      <ul>
      <% participant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location, id: :participant_location %>
  </div>

  <div class="field">
    <%= form.label :duration_of_stay %>
    <%= form.number_field :duration_of_stay, id: :participant_duration_of_stay %>
  </div>

  <div class="field">
    <%= form.label :amount_of_garbage %>
    <%= form.number_field :amount_of_garbage, id: :participant_amount_of_garbage %>
  </div>

  <div class="field">
    <%= form.label :recycling_knowledge1 %>
    <%= form.text_field :recycling_knowledge1, id: :participant_recycling_knowledge1 %>
  </div>

  <div class="field">
    <%= form.label :recycling_knowledge2 %>
    <%= form.text_field :recycling_knowledge2, id: :participant_recycling_knowledge2 %>
  </div>

  <div class="field">
    <%= form.label :if_they_recycle %>
    <%= form.check_box :if_they_recycle, id: :participant_if_they_recycle %>
  </div>

  <div class="field">
    <%= form.label :if_they_recycle_in_IGC %>
    <%= form.check_box :if_they_recycle_in_IGC, id: :participant_if_they_recycle_in_IGC %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/participants/edit.html.erb
<h1>Editing Participant</h1>

<%= render 'form', participant: @participant %>

<%= link_to 'Show', @participant %> |
<%= link_to 'Back', participants_path %>

app/views/participants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Participants</h1>

<table>
  <thead>
    <tr>
      <th>Location</th>
      <th>Duration of stay</th>
      <th>Amount of garbage</th>
      <th>Recycling knowledge1</th>
      <th>Recycling knowledge2</th>
      <th>If they recycle</th>
      <th>If they recycle in igc</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @participants.each do |participant| %>
      <tr>
        <td><%= participant.location %></td>
        <td><%= participant.duration_of_stay %></td>
        <td><%= participant.amount_of_garbage %></td>
        <td><%= participant.recycling_knowledge1 %></td>
        <td><%= participant.recycling_knowledge2 %></td>
        <td><%= participant.if_they_recycle %></td>
        <td><%= participant.if_they_recycle_in_IGC %></td>
        <td><%= link_to 'Show', participant %></td>
        <td><%= link_to 'Edit', edit_participant_path(participant) %></td>
        <td><%= button_to 'Destroy', participant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<br><%= link_to 'Table of Contents', 'http://localhost:3000/' %><br>

app/views/participants/new.html.erb
<h1>New Participant</h1>

<%= render 'form', participant: @participant %>

<%= link_to 'Back', participants_path %>

app/views/participants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Location:</strong>
  <%= @participant.location %>
</p>

<p>
  <strong>Duration of stay:</strong>
  <%= @participant.duration_of_stay %>
</p>

<p>
  <strong>Amount of garbage:</strong>
  <%= @participant.amount_of_garbage %>
</p>

<p>
  <strong>Recycling knowledge1:</strong>
  <%= @participant.recycling_knowledge1 %>
</p>

<p>
  <strong>Recycling knowledge2:</strong>
  <%= @participant.recycling_knowledge2 %>
</p>

<p>
  <strong>If they recycle:</strong>
  <%= @participant.if_they_recycle %>
</p>

<p>
  <strong>If they recycle in igc:</strong>
  <%= @participant.if_they_recycle_in_IGC %>
</p>

<%= link_to 'Edit', edit_participant_path(@participant) %> |
<%= link_to 'Back', participants_path %>