config/routes.rb
Rails.application.routes.draw do
  get 'explore/if_they_recycle'
  get 'explore/amount_of_garbage'
  get 'explore/satisfaction'
  get 'explore/table_of_contents'
  get 'explore/analysis'
  get 'team_data/load'
  get 'participants/index'
  get 'recyclers/index'
  get 'non_recyclers/index'
  
  resources :participants
  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :non_recyclers
  resources :recyclers
  resources :blogs
  
  root to: "explore#table_of_contents"
  
  
end

app/models/non_recycler.rb
class NonRecycler < ApplicationRecord
  belongs_to :participant
end

app/controllers/non_recyclers_controller.rb
class NonRecyclersController < ApplicationController
  before_action :set_non_recycler, only: [:show, :edit, :update, :destroy]

  # GET /non_recyclers
  # GET /non_recyclers.json
  def index
    @non_recyclers = NonRecycler.all
  end

  # GET /non_recyclers/1
  # GET /non_recyclers/1.json
  def show
  end

  # GET /non_recyclers/new
  def new
    @non_recycler = NonRecycler.new
  end

  # GET /non_recyclers/1/edit
  def edit
  end

  # POST /non_recyclers
  # POST /non_recyclers.json
  def create
    @non_recycler = NonRecycler.new(non_recycler_params)

    respond_to do |format|
      if @non_recycler.save
        format.html { redirect_to @non_recycler, notice: 'Non recycler was successfully created.' }
        format.json { render :show, status: :created, location: @non_recycler }
      else
        format.html { render :new }
        format.json { render json: @non_recycler.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /non_recyclers/1
  # PATCH/PUT /non_recyclers/1.json
  def update
    respond_to do |format|
      if @non_recycler.update(non_recycler_params)
        format.html { redirect_to @non_recycler, notice: 'Non recycler was successfully updated.' }
        format.json { render :show, status: :ok, location: @non_recycler }
      else
        format.html { render :edit }
        format.json { render json: @non_recycler.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /non_recyclers/1
  # DELETE /non_recyclers/1.json
  def destroy
    @non_recycler.destroy
    respond_to do |format|
      format.html { redirect_to non_recyclers_url, notice: 'Non recycler was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_non_recycler
      @non_recycler = NonRecycler.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def non_recycler_params
      params.require(:non_recycler).permit(:why_no_recycle, :improvements, :suggestion, :participants_id)
    end
end

app/helpers/non_recyclers_helper.rb
module NonRecyclersHelper
end

app/views/non_recyclers/_form.html.erb
<%= form_with(model: non_recycler, local: true) do |form| %>
  <% if non_recycler.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(non_recycler.errors.count, "error") %> prohibited this non_recycler from being saved:</h2>

      <ul>
      <% non_recycler.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :why_no_recycle %>
    <%= form.text_field :why_no_recycle, id: :non_recycler_why_no_recycle %>
  </div>

  <div class="field">
    <%= form.label :improvements %>
    <%= form.text_field :improvements, id: :non_recycler_improvements %>
  </div>

  <div class="field">
    <%= form.label :suggestion %>
    <%= form.text_field :suggestion, id: :non_recycler_suggestion %>
  </div>

  <div class="field">
    <%= form.label :participants_id %>
    <%= form.text_field :participants_id, id: :non_recycler_participants_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/non_recyclers/edit.html.erb
<h1>Editing Non Recycler</h1>

<%= render 'form', non_recycler: @non_recycler %>

<%= link_to 'Show', @non_recycler %> |
<%= link_to 'Back', non_recyclers_path %>

app/views/non_recyclers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Non Recyclers</h1>

<table>
  <thead>
    <tr>
      <th>Why no recycle</th>
      <th>Improvements</th>
      <th>Suggestion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @non_recyclers.each do |non_recycler| %>
      <tr>
        <td><%= non_recycler.why_no_recycle %></td>
        <td><%= non_recycler.improvements %></td>
        <td><%= non_recycler.suggestion %></td>
        <td><%= link_to 'Show', non_recycler %></td>
        <td><%= link_to 'Edit', edit_non_recycler_path(non_recycler) %></td>
        <td><%= link_to 'Destroy', non_recycler, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<br><%= link_to 'Table of Contents', 'http://localhost:3000/' %><br>

app/views/non_recyclers/new.html.erb
<h1>New Non Recycler</h1>

<%= render 'form', non_recycler: @non_recycler %>

<%= link_to 'Back', non_recyclers_path %>

app/views/non_recyclers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Why no recycle:</strong>
  <%= @non_recycler.why_no_recycle %>
</p>

<p>
  <strong>Improvements:</strong>
  <%= @non_recycler.improvements %>
</p>

<p>
  <strong>Suggestion:</strong>
  <%= @non_recycler.suggestion %>
</p>

<p>
  <strong>Participants:</strong>
  <%= @non_recycler.participants %>
</p>

<%= link_to 'Edit', edit_non_recycler_path(@non_recycler) %> |
<%= link_to 'Back', non_recyclers_path %>