config/routes.rb
Rails.application.routes.draw do
  get 'explore/if_they_recycle'
  get 'explore/amount_of_garbage'
  get 'explore/satisfaction'
  get 'explore/table_of_contents'
  get 'explore/analysis'
  get 'team_data/load'
  get 'participants/index'
  get 'recyclers/index'
  get 'non_recyclers/index'
  
  resources :participants
  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :non_recyclers
  resources :recyclers
  resources :blogs
  
  root to: "explore#table_of_contents"
  
  
end

app/models/recycler.rb
class Recycler < ApplicationRecord
  belongs_to :participant
end

app/controllers/recyclers_controller.rb
class RecyclersController < ApplicationController
  before_action :set_recycler, only: [:show, :edit, :update, :destroy]

  # GET /recyclers
  # GET /recyclers.json
  def index
    @recyclers = Recycler.all
  end

  # GET /recyclers/1
  # GET /recyclers/1.json
  def show
  end

  # GET /recyclers/new
  def new
    @recycler = Recycler.new
  end

  # GET /recyclers/1/edit
  def edit
  end

  # POST /recyclers
  # POST /recyclers.json
  def create
    @recycler = Recycler.new(recycler_params)

    respond_to do |format|
      if @recycler.save
        format.html { redirect_to @recycler, notice: 'Recycler was successfully created.' }
        format.json { render :show, status: :created, location: @recycler }
      else
        format.html { render :new }
        format.json { render json: @recycler.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recyclers/1
  # PATCH/PUT /recyclers/1.json
  def update
    respond_to do |format|
      if @recycler.update(recycler_params)
        format.html { redirect_to @recycler, notice: 'Recycler was successfully updated.' }
        format.json { render :show, status: :ok, location: @recycler }
      else
        format.html { render :edit }
        format.json { render json: @recycler.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recyclers/1
  # DELETE /recyclers/1.json
  def destroy
    @recycler.destroy
    respond_to do |format|
      format.html { redirect_to recyclers_url, notice: 'Recycler was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recycler
      @recycler = Recycler.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recycler_params
      params.require(:recycler).permit(:satisfaction, :satisfaction_why, :improvements, :suggestion, :participants_id)
    end
end

app/helpers/recyclers_helper.rb
module RecyclersHelper
end

app/views/recyclers/_form.html.erb
<%= form_with(model: recycler, local: true) do |form| %>
  <% if recycler.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recycler.errors.count, "error") %> prohibited this recycler from being saved:</h2>

      <ul>
      <% recycler.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :satisfaction %>
    <%= form.number_field :satisfaction, id: :recycler_satisfaction %>
  </div>

  <div class="field">
    <%= form.label :satisfaction_why %>
    <%= form.text_field :satisfaction_why, id: :recycler_satisfaction_why %>
  </div>

  <div class="field">
    <%= form.label :improvements %>
    <%= form.text_field :improvements, id: :recycler_improvements %>
  </div>

  <div class="field">
    <%= form.label :suggestion %>
    <%= form.text_field :suggestion, id: :recycler_suggestion %>
  </div>

  <div class="field">
    <%= form.label :participants_id %>
    <%= form.text_field :participants_id, id: :recycler_participants_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/recyclers/edit.html.erb
<h1>Editing Recycler</h1>

<%= render 'form', recycler: @recycler %>

<%= link_to 'Show', @recycler %> |
<%= link_to 'Back', recyclers_path %>

app/views/recyclers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recyclers</h1>

<table>
  <thead>
    <tr>
      <th>Satisfaction</th>
      <th>Satisfaction why</th>
      <th>Improvements</th>
      <th>Suggestion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recyclers.each do |recycler| %>
      <tr>
        <td><%= recycler.satisfaction %></td>
        <td><%= recycler.satisfaction_why %></td>
        <td><%= recycler.improvements %></td>
        <td><%= recycler.suggestion %></td>
        <td><%= link_to 'Show', recycler %></td>
        <td><%= link_to 'Edit', edit_recycler_path(recycler) %></td>
        <td><%= link_to 'Destroy', recycler, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<br><%= link_to 'Table of Contents', 'http://localhost:3000/' %><br>

app/views/recyclers/new.html.erb
<h1>New Recycler</h1>

<%= render 'form', recycler: @recycler %>

<%= link_to 'Back', recyclers_path %>

app/views/recyclers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Satisfaction:</strong>
  <%= @recycler.satisfaction %>
</p>

<p>
  <strong>Satisfaction why:</strong>
  <%= @recycler.satisfaction_why %>
</p>

<p>
  <strong>Improvements:</strong>
  <%= @recycler.improvements %>
</p>

<p>
  <strong>Suggestion:</strong>
  <%= @recycler.suggestion %>
</p>

<p>
  <strong>Participants:</strong>
  <%= @recycler.participants %>
</p>

<%= link_to 'Edit', edit_recycler_path(@recycler) %> |
<%= link_to 'Back', recyclers_path %>